version: "3.3"
services:
  base:
    image: tuttlebr/face-recognition:00-base-${BUILD_VERSION}
    volumes:
      - type: bind
        source: ${PHOTO_DIR}
        target: /photos
    build:
      context: app
      dockerfile: Dockerfile
      args:
        - NV_TENSORFLOW_BUILD=${NV_TENSORFLOW_BUILD}
        - CORE_COUNT=${CORE_COUNT}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]